### ISSUE TITLE
Número de semana en delete_old_backups

### ISSUE THREAD

**Issue by LisandroSeijo** [yograterol/zoort#1]
En el método delete_old_backups, se toma el número de la semana y se le resta directamente 2, esto hace que que la primer y segunda semana del año el resultado de -1 y 0, las últimas dos semanas del año (51 y 52) quedarían sin borrar.

Se podría solucionar verificando primero qué vador da:

``` python
def delete_old_backups(bucket):
    thisweek = datetime.datetime.now().isocalendar()[1]
    if thisweek < 3
        """
        Si dio 1: 52 + 1 = 53 (borra la semana 51)
        Si dio 2: 52 + 2 = 54 (borra la semana 52)
        """
        thisweek += 52

    week = str(thisweek - 2)
```

No sé si ya lo habían tenido en cuenta a ese detalle.

**Comment by yograterol** [comment]
Tienes razón, muchas gracias por tu aporte, ya lo agrego, se me paso ese detalle.

**Comment by yograterol** [comment]
Los cambios se han hecho en este commit: https://github.com/yograterol/zoort/commit/305e68bf5523de5c270fe26b469f4bf79791d80a.

Muchas gracias por la revisión.

**Comment by LisandroSeijo** [comment]
Un gusto @yograterol 

Me faltaron los : en el if.
