### ISSUE TITLE
Cambio en la forma de guardar y eliminar los archivos

### ISSUE THREAD

**Issue by LisandroSeijo** [yograterol/zoort#2]
Hice unos cambios en la forma de guardar y eliminar los archivos:
Como se guarda ahora, si el proyecto se para o por cualquier razón pasan una semana sin hacer al menos un backup, los archivos almacenados dos semanas previas a esa/s no se borran hasta que el número de la semana coincida el próximo año.

Lo que hice fue en vez de usar el número de la semana, puse los segundos transcurridos (estándar, desde 1970). Asi calcula la diferencia de tiempo con todos los archivos y elimina todos los que haya fuera de ese rango sin dejar ninguno y evitar la inconcistencia.

También agregué dos globales, un booleano DELETE_BACKUP para poder ponerlo en falso si es que no quieren borrar los archivos, y DELETE_WEEKS con el número de semanas que se van a guardar, para poder cambiarlo por las semanas que quieran.

No mando el pull request porque al cambiar el nombre de los archivos, si ya se está usando en producción el cambio es más delicado. Pero si les parece bien lo mando.

Pueden verlo acá: https://github.com/LisandroSeijo/zoort/compare/new_delete

**Comment by yograterol** [comment]
Muchas gracias LisandroSeijo, me parece bien tu propuesta.

Crea el Pull, para revisarte el código y decirte algunos cambios.

**Comment by LisandroSeijo** [comment]
Hecho

**Comment by yograterol** [comment]
Pull Request asignado:https://github.com/yograterol/zoort/pull/3

**Comment by yograterol** [comment]
Issue resuelto.
