### ISSUE TITLE
Compatibilidad con Amazon Glacier

### ISSUE THREAD

**Issue by yograterol** [yograterol/zoort#4]
Ya que AWS provee un servicio destinado a respaldos llamado Amazon Glacier, sería ideal agregarle el soporte para ese servicio manteniendo el de Amazon S3.

**Comment by LisandroSeijo** [comment]
Qué tal esto, se hace un paquete de "uploaders" para poder elegir adonde lo quieren subir, se puede empezar con S3 que ya estaría, solo falta pasar el código a una clase, agregar el de Amazon Glacier, uno para Dropbox, y uno para subirlo por FTP, como para arrancar.

Heredarían de una clase base para obligarlos a tener los métodos upload, que recibe el archivo y un array con los parámetros que necesite el servicio en específico, y delete que borra los viejos.

Y asi cada uno va agregando el soporte al servicio que use si todavía no está hecho.

**Comment by yograterol** [comment]
Si me parece bastante correcto hacerlo, te apoyo, voy hacerlo así.

**Comment by yograterol** [comment]
Apliqué Factory Pattern para definir los "uploaders" y agregué la compatibilidad a Glacier, está en pruebas aún. Por allí viene compatibilidad con Swift de OpenStack.

**Comment by yograterol** [comment]
Sobre la clase tipo "instancia" (haciendo referencia a POO en lenguajes como Java o PHP), no es necesaria, con tener los métodos basta.
